import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ToasterProvider from '@/providers/ToasterProvider'
import { images, links } from './(adams)/utils'
import Text from './(adams)/components/(custom-components)/text'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <div>
                <ul className='flex flex-wrap justify-around'>
                    {links().map((link) => (
                        <Text key={link.name} size="xl" w="semibold" className="text-black">
                            {link.name}
                        </Text>
                    ))}
                </ul>
            </div> */}
             <div className='mt-[40px]'>
                        <Image src={images.navigation} alt='study image' className='' />
                    </div>
        <ToasterProvider />
        {children}
        </body>
    </html>
  )
}
